# Generated by Django 5.2.7 on 2025-10-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
